const fetch = require("node-fetch");
const catArr = [
  "computers",
  "laptops",
  "monitors",
  "pc-gaming",
  "components",
  "storage",
  "tablets",
  "software",
  "networking",
  "printers-scanners",
  "computer-accessories",
  "keyboards-mice",
  "ssd-solid-state-drives,tv-home-theater",
  "smartphones",
  "gaming",
  "headphones",
  "audio-components",
  "cameras-camcorders",
  "smart-home-devices",
  "wearable-tech",
  "apple-lightning-cables",
  "power-bank",
  "home-theater-tv-accessories",
  "mobile-accessories",
  "robot-vacuum",
  "sound-bar",
  "dash-cams",
  "office-electronics",
  "vr-headsets",
  "drones",
  "projectors",
  "tools",
  "clothing-shoes",
  "home-garden",
  "appliances-kitchen",
  "automotive-car-tech",
  "sporting-goods",
  "gift-cards",
  "travel",
  "health-beauty",
  "massagers",
  "air-purifier",
  "bed-bath",
  "food-restaurants",
  "entertainment",
  "video-streaming",
  "furniture",
  "toys-and-collectibles",
  "lego",
  "tires",
  "pets",
  "free-stuff,magazines-subscriptions",
  "mattresses-beds-frames",
  "vpn",
  "web-hosting",
  "refurbished",
  "finance",
  "tax-preparation",
  "home-office",
  "emergency-preparedness",
];

const storeArr = [
  "amazon",
  "walmart",
  "bestbuy",
  "dell",
  "dellsmallbiz",
  "verizon",
  "google-store",
  "lenovo",
  "rakuten",
  "b-and-h",
  "alienware",
  "newegg",
  "apple",
  "ebay",
  "pcmag-shop",
  "hp",
  "att-wireless",
  "tmobile",
  "microsoft",
  "sprint",
  "/",
];

const openConnection = async () => {
  for (el of catArr) {
    await fetch(`https://www.techbargains.com/categories/${el}`);
  }
  for (el of storeArr) {
    await fetch(`https://www.techbargains.com/stores/${el}`);
  }
};

module.exports = openConnection;
